version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./../postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guitarlions
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  django:
    build: .
    restart: always
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: ""
      SECRET_KEY: "secret"
      DB_HOST: db
      DB_NAME: "guitarlions"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
      DOMAIN: ""
      DOMAIN_URL: "https://"
      STATIC_URL: "/static/"
      MEDIA_URL: "/media/"
      EMAIL_USE_TLS: True
      EMAIL_HOST: ""
      EMAIL_USE_TLS: "True"
      EMAIL_PORT: "2525"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
    expose:
      - 8000
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - .:/usr/src/app/
        - ./Caddyfile.staging:/etc/caddy/Caddyfile
        - ./../caddy_data:/data
    depends_on:
      - django

  gulp:
    build: Dockerfiles/gulp
    restart: always
    command: gulp
    volumes:
        - .:/app/
    depends_on:
      - caddy
